version: "3.9"
services:
  web:
    build: .
    volumes:
      - .:/simple_todo
      - ./node_modules:/simple_todo/node_modules
    # command: node index.js
    ports:
      - 8000:1234
    tty: true 
    stdin_open: true
