version: "3.9"
services:
  web:
    build: .
    volumes:
      - .:/simple_todo
      - ./node_modules:/simple_todo/node_modules
    # command: node index.js
    ports:
      - 8000:1234
    env_file: ./.env.development
    tty: true
    stdin_open: true
  mysql:
    image: mysql:8.0.28
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: simple_todo
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql:/var/lib/mysql
